
spring:
  jpa:
    hibernate:
      ddl-auto: update
  #  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    # Has to be overwritten on deployment!
    url: jdbc:postgresql://${DB_ROOT:localhost}:5432/endstation_beverage_maschine_service
    username: overwrite
    password: overwrite
    driver-class-name: org.postgresql.Driver

