
spring:
  jpa:
    hibernate:
      ddl-auto: update
  #  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    # Has to be overwritten on deployment!
    url: jdbc:postgresql://172.21.0.2:5432/endstation_beverage_maschine_service
    username: sa
    # Has to be overwritten on deployment!
    password: sa
    driver-class-name: org.postgresql.Driver

