services:
  postgres:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U postgres
    networks:
      beverage-machine-network:
        ipv4_address: 172.21.0.2
  beverage-machine-service:
    image: endstation-beverage-maschine-service:0.0.1-SNAPSHOT
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_ROOT: 172.21.0.2
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
    ports:
      - '8080:8080'
    networks:
      - beverage-machine-network
networks:
  beverage-machine-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
    external: false
